language: minimal

sudo: required

services:
  - docker

script:
  - ./.travis-ci/build-docker.sh
  - ./.travis-ci/test-docker.sh

#after_success:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker push $DOCKER_USERNAME/$REPO

deploy:
  provider: script
  script: ./.travis-ci/deploy-docker.sh
  on:
    all_branches: true
  skip_cleanup: true
