language: generic

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker build -t shylockhg/dev .

script:
  - docker run shylockhg/dev

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$REPO
