language: minimal

sudo: required

services:
  - docker

script:
  - ./.travis-ci/build-docker.sh
  - ./.travis-ci/test-docker.sh

deploy:
  provider: script
  script: ./.travis-ci/deploy-docker.sh
  on:
    branch: master
  skip_cleanup: true
