nerdtree:
  recipe: ''
  url: https://github.com/scrooloose/nerdtree.git
nerdtree-git-plugin:
  recipe: ''
  url: https://github.com/xuyuanp/nerdtree-git-plugin.git
tagbar:
  recipe: ''
  url: https://github.com/majutsushi/tagbar.git
vim-airline:
  recipe: ''
  url: https://github.com/vim-airline/vim-airline.git
vim-airline-themes:
  recipe: ''
  url: https://github.com/vim-airline/vim-airline-themes.git
vim-colors-solarized:
  recipe: ''
  url: https://github.com/altercation/vim-colors-solarized.git
vim-fugitive:
  recipe: ''
  url: https://github.com/tpope/vim-fugitive.git
