version: '3'
services:
    dev:
        image: "shylockhg/dev"
        volumes:
            - "/run/postgresql:/run/postgresql/"
        stdin_open: true
        tty: true
    postgres:
        image: postgres
        volumes:
            - "/run/postgresql:/run/postgresql/"
        restart: always
